version: '3'

volumes:
  vendor:

services:
  api:
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    volumes:
      - ./src/api:/go/src/api
      - vendor:/go/src/api/vendor
    ports:
      - 8080:8080
    tty:
      true
